#!/bin/sh /etc/rc.common

START=98
STOP=10
USE_PROCD=1

SERVICE_BIN="/usr/bin/xiass-soft-router-agent"

start_service() {
	"$SERVICE_BIN" --is-enabled >/dev/null 2>&1 || return 0

	procd_open_instance "agent"
	procd_set_param command "$SERVICE_BIN"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "xiass_soft_router_agent"
	procd_add_reload_trigger "nowind_soft_router_agent"
}

reload_service() {
	stop
	start
}

stop_service() {
	"$SERVICE_BIN" --stop-frpc >/dev/null 2>&1 || true
}
